trigger:
  branches:
    include:
      - main
  tags:
    include: ['*']
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishExtension
    displayName: 🚀 Publish Extension
    type: boolean
    default: false

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    workingDirectory: packages/vscode-js-profile-table
    publishExtension: ${{ parameters.publishExtension }}
    vscePackageArgs: --no-dependencies
    ghCreateRelease: true
    ghReleaseAddChangeLog: true
    buildSteps:
      - script: npm ci
        displayName: Install dependencies

      - script: npm run compile
        displayName: Install dependencies
