// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/initializers/zero_initializer_attrs.struct.toml
/* proj-data
{
  "generated_from": "a19d5a2cdc67a2840d6ba55250a10411"
}
*/

#include "pcg/initializers/zero_initializer_attrs.dtg.h"

#include <sstream>

namespace FlexFlow {
bool ZeroInitializerAttrs::operator==(ZeroInitializerAttrs const &other) const {
  return std::tie() == std::tie();
}
bool ZeroInitializerAttrs::operator!=(ZeroInitializerAttrs const &other) const {
  return std::tie() != std::tie();
}
bool ZeroInitializerAttrs::operator<(ZeroInitializerAttrs const &other) const {
  return std::tie() < std::tie();
}
bool ZeroInitializerAttrs::operator>(ZeroInitializerAttrs const &other) const {
  return std::tie() > std::tie();
}
bool ZeroInitializerAttrs::operator<=(ZeroInitializerAttrs const &other) const {
  return std::tie() <= std::tie();
}
bool ZeroInitializerAttrs::operator>=(ZeroInitializerAttrs const &other) const {
  return std::tie() >= std::tie();
}
} // namespace FlexFlow

namespace std {
size_t hash<FlexFlow::ZeroInitializerAttrs>::operator()(
    FlexFlow::ZeroInitializerAttrs const &x) const {
  size_t result = 0;
  return result;
}
} // namespace std

namespace nlohmann {
FlexFlow::ZeroInitializerAttrs
    adl_serializer<FlexFlow::ZeroInitializerAttrs>::from_json(json const &j) {
  return {};
}
void adl_serializer<FlexFlow::ZeroInitializerAttrs>::to_json(
    json &j, FlexFlow::ZeroInitializerAttrs const &v) {
  j["__type"] = "ZeroInitializerAttrs";
}
} // namespace nlohmann

namespace rc {
Gen<FlexFlow::ZeroInitializerAttrs>
    Arbitrary<FlexFlow::ZeroInitializerAttrs>::arbitrary() {
  return gen::construct<FlexFlow::ZeroInitializerAttrs>();
}
} // namespace rc

namespace FlexFlow {
std::string format_as(ZeroInitializerAttrs const &x) {
  std::ostringstream oss;
  oss << "<ZeroInitializerAttrs";
  oss << ">";
  return oss.str();
}
std::ostream &operator<<(std::ostream &s, ZeroInitializerAttrs const &x) {
  return s << fmt::to_string(x);
}
} // namespace FlexFlow
