#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OPEN_PARALLEL_TENSOR_GUID_T_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OPEN_PARALLEL_TENSOR_GUID_T_H

#include "pcg/parallel_computation_graph/parallel_tensor_guid_t.dtg.h"
#include "substitutions/open_parallel_tensor_guid_t.dtg.h"
#include "substitutions/input_parallel_tensor_guid_t.dtg.h"

namespace FlexFlow {

open_parallel_tensor_guid_t open_parallel_tensor_guid_from_closed(parallel_tensor_guid_t);
open_parallel_tensor_guid_t open_parallel_tensor_guid_from_input(input_parallel_tensor_guid_t);

} // namespace FlexFlow

#endif
