// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/batch_norm_attrs.struct.toml
/* proj-data
{
  "generated_from": "f8e0219d8a3e008a73c38cf84d25f66e"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_BATCH_NORM_ATTRS_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_BATCH_NORM_ATTRS_DTG_H

#include "fmt/format.h"
#include "nlohmann/json.hpp"
#include "rapidcheck.h"
#include <functional>
#include <ostream>
#include <tuple>

namespace FlexFlow {
struct BatchNormAttrs {
  BatchNormAttrs() = delete;
  BatchNormAttrs(bool const &relu);

  bool operator==(BatchNormAttrs const &) const;
  bool operator!=(BatchNormAttrs const &) const;
  bool operator<(BatchNormAttrs const &) const;
  bool operator>(BatchNormAttrs const &) const;
  bool operator<=(BatchNormAttrs const &) const;
  bool operator>=(BatchNormAttrs const &) const;
  bool relu;
};
} // namespace FlexFlow

namespace std {
template <>
struct hash<FlexFlow::BatchNormAttrs> {
  size_t operator()(FlexFlow::BatchNormAttrs const &) const;
};
} // namespace std

namespace nlohmann {
template <>
struct adl_serializer<FlexFlow::BatchNormAttrs> {
  static FlexFlow::BatchNormAttrs from_json(json const &);
  static void to_json(json &, FlexFlow::BatchNormAttrs const &);
};
} // namespace nlohmann

namespace rc {
template <>
struct Arbitrary<FlexFlow::BatchNormAttrs> {
  static Gen<FlexFlow::BatchNormAttrs> arbitrary();
};
} // namespace rc

namespace FlexFlow {
std::string format_as(BatchNormAttrs const &);
std::ostream &operator<<(std::ostream &, BatchNormAttrs const &);
} // namespace FlexFlow

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_BATCH_NORM_ATTRS_DTG_H
