// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/digraph/di_output.struct.toml
/* proj-data
{
  "generated_from": "a8f3fc2ad9e00f3c29a6dcd4658199ba"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DIGRAPH_DI_OUTPUT_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DIGRAPH_DI_OUTPUT_DTG_H

#include "utils/graph/node.dtg.h"
#include <functional>
#include <tuple>

namespace FlexFlow {
struct DiOutput {
  DiOutput() = delete;
  explicit DiOutput(::FlexFlow::Node const &src);

  bool operator==(DiOutput const &) const;
  bool operator!=(DiOutput const &) const;
  bool operator<(DiOutput const &) const;
  bool operator>(DiOutput const &) const;
  bool operator<=(DiOutput const &) const;
  bool operator>=(DiOutput const &) const;
  ::FlexFlow::Node src;
};
} // namespace FlexFlow

namespace std {
template <>
struct hash<::FlexFlow::DiOutput> {
  size_t operator()(::FlexFlow::DiOutput const &) const;
};
} // namespace std

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DIGRAPH_DI_OUTPUT_DTG_H
