

cmake -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DFF_CUDA_ARCH=75 -DCMAKE_CUDA_ARCHITECTURES=75 -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_C_COMPILER="clang" -DCMAKE_CUDA_COMPILER="clang++" -DCMAKE_CUDA_HOST_COMPILER="clang++" ..