namespace = "FlexFlow"
name = "JsonSPModelExport"
features = [
  "eq",
  "hash",
  "fmt",
  "json", 
]

includes = [
  "pcg/file_format/v1/v1_computation_graph.dtg.h",
  "utils/graph/series_parallel/binary_sp_decomposition_tree/leaf_only_binary_sp_decomposition_tree/leaf_only_binary_sp_decomposition_tree.dtg.h",
]

src_includes = [
  "utils/graph/series_parallel/binary_sp_decomposition_tree/leaf_only_binary_sp_decomposition_tree/json.h",
]

[[fields]]
name = "sp_decomposition"
type = "::FlexFlow::LeafOnlyBinarySPDecompositionTree<int>"

[[fields]]
name = "computation_graph"
type = "::FlexFlow::V1ComputationGraph"
