namespace = "FlexFlow"
name = "JsonSPModelExport"
features = [
  "eq",
  "hash",
  "json",
  "fmt",
]

includes = [
  "pcg/file_format/v1/v1_computation_graph.dtg.h",
  "utils/graph/serial_parallel/binary_sp_decomposition_tree/binary_sp_decomposition_tree.h",
]

[[fields]]
name = "sp_decomposition"
type = "::FlexFlow::GenericBinarySPDecompositionTree<int>"

[[fields]]
name = "computation_graph"
type = "::FlexFlow::V1ComputationGraph"
