// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/file_format/v1/graphs/v1_operator_graph.struct.toml
/* proj-data
{
  "generated_from": "fed215ca219af1bd375801eb2e33b473"
}
*/

#include "pcg/file_format/v1/graphs/v1_operator_graph.dtg.h"

#include <sstream>

namespace FlexFlow {
V1OperatorGraph::V1OperatorGraph(
    std::vector<size_t> const &nodes,
    std::unordered_set<::FlexFlow::V1GraphEdge> const &edges)
    : nodes(nodes), edges(edges) {}
} // namespace FlexFlow

namespace nlohmann {
::FlexFlow::V1OperatorGraph
    adl_serializer<::FlexFlow::V1OperatorGraph>::from_json(json const &j) {
  return ::FlexFlow::V1OperatorGraph{
      j.at("nodes").template get<std::vector<size_t>>(),
      j.at("edges")
          .template get<std::unordered_set<::FlexFlow::V1GraphEdge>>()};
}
void adl_serializer<::FlexFlow::V1OperatorGraph>::to_json(
    json &j, ::FlexFlow::V1OperatorGraph const &v) {
  j["__type"] = "V1OperatorGraph";
  j["nodes"] = v.nodes;
  j["edges"] = v.edges;
}
} // namespace nlohmann

namespace FlexFlow {
std::string format_as(V1OperatorGraph const &x) {
  std::ostringstream oss;
  oss << "<V1OperatorGraph";
  oss << " nodes=" << x.nodes;
  oss << " edges=" << x.edges;
  oss << ">";
  return oss.str();
}
std::ostream &operator<<(std::ostream &s, V1OperatorGraph const &x) {
  return s << fmt::to_string(x);
}
} // namespace FlexFlow
