// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/computation_graph.struct.toml
/* proj-data
{
  "generated_from": "79ce58a361b164cad98643f961b9e266"
}
*/

#include "pcg/computation_graph.dtg.h"

namespace FlexFlow {
ComputationGraph::ComputationGraph(
    ::FlexFlow::LabelledDataflowGraph<::FlexFlow::LayerAttrs,
                                      ::FlexFlow::TensorAttrs> const &raw_graph)
    : raw_graph(raw_graph) {}
} // namespace FlexFlow
