// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/cpu_id_t.struct.toml
/* proj-data
{
  "generated_from": "a0faf78831febfa3a02929169943d9f5"
}
*/

#include "pcg/cpu_id_t.dtg.h"

#include <sstream>

namespace FlexFlow {
cpu_id_t::cpu_id_t(int const &cpu_index) : cpu_index(cpu_index) {}
bool cpu_id_t::operator==(cpu_id_t const &other) const {
  return std::tie(this->cpu_index) == std::tie(other.cpu_index);
}
bool cpu_id_t::operator!=(cpu_id_t const &other) const {
  return std::tie(this->cpu_index) != std::tie(other.cpu_index);
}
bool cpu_id_t::operator<(cpu_id_t const &other) const {
  return std::tie(this->cpu_index) < std::tie(other.cpu_index);
}
bool cpu_id_t::operator>(cpu_id_t const &other) const {
  return std::tie(this->cpu_index) > std::tie(other.cpu_index);
}
bool cpu_id_t::operator<=(cpu_id_t const &other) const {
  return std::tie(this->cpu_index) <= std::tie(other.cpu_index);
}
bool cpu_id_t::operator>=(cpu_id_t const &other) const {
  return std::tie(this->cpu_index) >= std::tie(other.cpu_index);
}
} // namespace FlexFlow

namespace std {
size_t hash<FlexFlow::cpu_id_t>::operator()(FlexFlow::cpu_id_t const &x) const {
  size_t result = 0;
  result ^= std::hash<int>{}(x.cpu_index) + 0x9e3779b9 + (result << 6) +
            (result >> 2);
  return result;
}
} // namespace std

namespace nlohmann {
FlexFlow::cpu_id_t
    adl_serializer<FlexFlow::cpu_id_t>::from_json(json const &j) {
  return {j.at("cpu_index").template get<int>()};
}
void adl_serializer<FlexFlow::cpu_id_t>::to_json(json &j,
                                                 FlexFlow::cpu_id_t const &v) {
  j["__type"] = "cpu_id_t";
  j["cpu_index"] = v.cpu_index;
}
} // namespace nlohmann

namespace rc {
Gen<FlexFlow::cpu_id_t> Arbitrary<FlexFlow::cpu_id_t>::arbitrary() {
  return gen::construct<FlexFlow::cpu_id_t>(gen::arbitrary<int>());
}
} // namespace rc

namespace FlexFlow {
std::string format_as(cpu_id_t const &x) {
  std::ostringstream oss;
  oss << "<cpu_id_t";
  oss << " cpu_index=" << x.cpu_index;
  oss << ">";
  return oss.str();
}
std::ostream &operator<<(std::ostream &s, cpu_id_t const &x) {
  return s << fmt::to_string(x);
}
} // namespace FlexFlow
