// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/parallel_tensor_attrs.struct.toml
/* proj-data
{
  "generated_from": "b3e086b380bbc41d99332e1463a34b28"
}
*/

#include "pcg/parallel_tensor_attrs.dtg.h"

#include "op-attrs/parallel_tensor_shape.dtg.h"
#include "op-attrs/param_sync.dtg.h"
#include "pcg/create_grad.dtg.h"
#include "pcg/initializer_attrs.dtg.h"
#include <optional>
#include <sstream>

namespace FlexFlow {
ParallelTensorAttrs::ParallelTensorAttrs(
    ::FlexFlow::ParallelTensorShape const &shape,
    std::optional<::FlexFlow::ParamSync> const &sync_type,
    std::optional<::FlexFlow::InitializerAttrs> const &initializer,
    ::FlexFlow::CreateGrad const &create_gradients)
    : shape(shape), sync_type(sync_type), initializer(initializer),
      create_gradients(create_gradients) {}
bool ParallelTensorAttrs::operator==(ParallelTensorAttrs const &other) const {
  return std::tie(this->shape,
                  this->sync_type,
                  this->initializer,
                  this->create_gradients) == std::tie(other.shape,
                                                      other.sync_type,
                                                      other.initializer,
                                                      other.create_gradients);
}
bool ParallelTensorAttrs::operator!=(ParallelTensorAttrs const &other) const {
  return std::tie(this->shape,
                  this->sync_type,
                  this->initializer,
                  this->create_gradients) != std::tie(other.shape,
                                                      other.sync_type,
                                                      other.initializer,
                                                      other.create_gradients);
}
bool ParallelTensorAttrs::operator<(ParallelTensorAttrs const &other) const {
  return std::tie(this->shape,
                  this->sync_type,
                  this->initializer,
                  this->create_gradients) < std::tie(other.shape,
                                                     other.sync_type,
                                                     other.initializer,
                                                     other.create_gradients);
}
bool ParallelTensorAttrs::operator>(ParallelTensorAttrs const &other) const {
  return std::tie(this->shape,
                  this->sync_type,
                  this->initializer,
                  this->create_gradients) > std::tie(other.shape,
                                                     other.sync_type,
                                                     other.initializer,
                                                     other.create_gradients);
}
bool ParallelTensorAttrs::operator<=(ParallelTensorAttrs const &other) const {
  return std::tie(this->shape,
                  this->sync_type,
                  this->initializer,
                  this->create_gradients) <= std::tie(other.shape,
                                                      other.sync_type,
                                                      other.initializer,
                                                      other.create_gradients);
}
bool ParallelTensorAttrs::operator>=(ParallelTensorAttrs const &other) const {
  return std::tie(this->shape,
                  this->sync_type,
                  this->initializer,
                  this->create_gradients) >= std::tie(other.shape,
                                                      other.sync_type,
                                                      other.initializer,
                                                      other.create_gradients);
}
} // namespace FlexFlow

namespace std {
size_t hash<FlexFlow::ParallelTensorAttrs>::operator()(
    FlexFlow::ParallelTensorAttrs const &x) const {
  size_t result = 0;
  result ^= std::hash<::FlexFlow::ParallelTensorShape>{}(x.shape) + 0x9e3779b9 +
            (result << 6) + (result >> 2);
  result ^= std::hash<std::optional<::FlexFlow::ParamSync>>{}(x.sync_type) +
            0x9e3779b9 + (result << 6) + (result >> 2);
  result ^=
      std::hash<std::optional<::FlexFlow::InitializerAttrs>>{}(x.initializer) +
      0x9e3779b9 + (result << 6) + (result >> 2);
  result ^= std::hash<::FlexFlow::CreateGrad>{}(x.create_gradients) +
            0x9e3779b9 + (result << 6) + (result >> 2);
  return result;
}
} // namespace std

namespace nlohmann {
FlexFlow::ParallelTensorAttrs
    adl_serializer<FlexFlow::ParallelTensorAttrs>::from_json(json const &j) {
  return {
      j.at("shape").template get<::FlexFlow::ParallelTensorShape>(),
      j.at("sync_type").template get<std::optional<::FlexFlow::ParamSync>>(),
      j.at("initializer")
          .template get<std::optional<::FlexFlow::InitializerAttrs>>(),
      j.at("create_gradients").template get<::FlexFlow::CreateGrad>()};
}
void adl_serializer<FlexFlow::ParallelTensorAttrs>::to_json(
    json &j, FlexFlow::ParallelTensorAttrs const &v) {
  j["__type"] = "ParallelTensorAttrs";
  j["shape"] = v.shape;
  j["sync_type"] = v.sync_type;
  j["initializer"] = v.initializer;
  j["create_gradients"] = v.create_gradients;
}
} // namespace nlohmann

namespace FlexFlow {
std::string format_as(ParallelTensorAttrs const &x) {
  std::ostringstream oss;
  oss << "<ParallelTensorAttrs";
  oss << " shape=" << x.shape;
  oss << " sync_type=" << x.sync_type;
  oss << " initializer=" << x.initializer;
  oss << " create_gradients=" << x.create_gradients;
  oss << ">";
  return oss.str();
}
std::ostream &operator<<(std::ostream &s, ParallelTensorAttrs const &x) {
  return s << fmt::to_string(x);
}
} // namespace FlexFlow
