// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/side_size_t.struct.toml
/* proj-data
{
  "generated_from": "6a1669890e547dcc7a4ddb90be05be15"
}
*/

#include "pcg/side_size_t.dtg.h"

#include <sstream>

namespace FlexFlow {
side_size_t::side_size_t(int const &unwrapped) : unwrapped(unwrapped) {}
bool side_size_t::operator==(side_size_t const &other) const {
  return std::tie(this->unwrapped) == std::tie(other.unwrapped);
}
bool side_size_t::operator!=(side_size_t const &other) const {
  return std::tie(this->unwrapped) != std::tie(other.unwrapped);
}
bool side_size_t::operator<(side_size_t const &other) const {
  return std::tie(this->unwrapped) < std::tie(other.unwrapped);
}
bool side_size_t::operator>(side_size_t const &other) const {
  return std::tie(this->unwrapped) > std::tie(other.unwrapped);
}
bool side_size_t::operator<=(side_size_t const &other) const {
  return std::tie(this->unwrapped) <= std::tie(other.unwrapped);
}
bool side_size_t::operator>=(side_size_t const &other) const {
  return std::tie(this->unwrapped) >= std::tie(other.unwrapped);
}
} // namespace FlexFlow

namespace std {
size_t hash<FlexFlow::side_size_t>::operator()(
    FlexFlow::side_size_t const &x) const {
  size_t result = 0;
  result ^= std::hash<int>{}(x.unwrapped) + 0x9e3779b9 + (result << 6) +
            (result >> 2);
  return result;
}
} // namespace std

namespace nlohmann {
FlexFlow::side_size_t
    adl_serializer<FlexFlow::side_size_t>::from_json(json const &j) {
  return {j.at("unwrapped").template get<int>()};
}
void adl_serializer<FlexFlow::side_size_t>::to_json(
    json &j, FlexFlow::side_size_t const &v) {
  j["__type"] = "side_size_t";
  j["unwrapped"] = v.unwrapped;
}
} // namespace nlohmann

namespace rc {
Gen<FlexFlow::side_size_t> Arbitrary<FlexFlow::side_size_t>::arbitrary() {
  return gen::construct<FlexFlow::side_size_t>(gen::arbitrary<int>());
}
} // namespace rc

namespace FlexFlow {
std::string format_as(side_size_t const &x) {
  std::ostringstream oss;
  oss << "<side_size_t";
  oss << " unwrapped=" << x.unwrapped;
  oss << ">";
  return oss.str();
}
std::ostream &operator<<(std::ostream &s, side_size_t const &x) {
  return s << fmt::to_string(x);
}
} // namespace FlexFlow
