// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/downward_open_dataflow_graph/dataflow_output_edge.struct.toml
/* proj-data
{
  "generated_from": "2488765bd934738ef9111699bb8b71e3"
}
*/

#include "utils/graph/downward_open_dataflow_graph/dataflow_output_edge.dtg.h"

#include <sstream>

namespace FlexFlow {
DataflowOutputEdge::DataflowOutputEdge(
    ::FlexFlow::DataflowOutput const &src,
    ::FlexFlow::DataflowGraphOutput const &dst)
    : src(src), dst(dst) {}
bool DataflowOutputEdge::operator==(DataflowOutputEdge const &other) const {
  return std::tie(this->src, this->dst) == std::tie(other.src, other.dst);
}
bool DataflowOutputEdge::operator!=(DataflowOutputEdge const &other) const {
  return std::tie(this->src, this->dst) != std::tie(other.src, other.dst);
}
bool DataflowOutputEdge::operator<(DataflowOutputEdge const &other) const {
  return std::tie(this->src, this->dst) < std::tie(other.src, other.dst);
}
bool DataflowOutputEdge::operator>(DataflowOutputEdge const &other) const {
  return std::tie(this->src, this->dst) > std::tie(other.src, other.dst);
}
bool DataflowOutputEdge::operator<=(DataflowOutputEdge const &other) const {
  return std::tie(this->src, this->dst) <= std::tie(other.src, other.dst);
}
bool DataflowOutputEdge::operator>=(DataflowOutputEdge const &other) const {
  return std::tie(this->src, this->dst) >= std::tie(other.src, other.dst);
}
} // namespace FlexFlow

namespace std {
size_t hash<FlexFlow::DataflowOutputEdge>::operator()(
    ::FlexFlow::DataflowOutputEdge const &x) const {
  size_t result = 0;
  result ^= std::hash<::FlexFlow::DataflowOutput>{}(x.src) + 0x9e3779b9 +
            (result << 6) + (result >> 2);
  result ^= std::hash<::FlexFlow::DataflowGraphOutput>{}(x.dst) + 0x9e3779b9 +
            (result << 6) + (result >> 2);
  return result;
}
} // namespace std

namespace FlexFlow {
std::string format_as(DataflowOutputEdge const &x) {
  std::ostringstream oss;
  oss << "<DataflowOutputEdge";
  oss << " src=" << x.src;
  oss << " dst=" << x.dst;
  oss << ">";
  return oss.str();
}
std::ostream &operator<<(std::ostream &s, DataflowOutputEdge const &x) {
  return s << fmt::to_string(x);
}
} // namespace FlexFlow
