#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_MACHINE_MAPPING_PROBLEM_TREE_MM_PROBLEM_TREE_PARALLEL_SPLIT_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_MACHINE_MAPPING_PROBLEM_TREE_MM_PROBLEM_TREE_PARALLEL_SPLIT_H

#include "compiler/machine_mapping/machine_mapping_problem_tree/machine_mapping_problem_tree.dtg.h"
#include "compiler/machine_mapping/machine_mapping_problem_tree/mm_problem_tree_parallel_split.dtg.h"

namespace FlexFlow {

MachineMappingProblemTree get_lhs_child(MMProblemTreeParallelSplit const &);
MachineMappingProblemTree get_rhs_child(MMProblemTreeParallelSplit const &);

} // namespace FlexFlow

#endif
