#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_ALGORITHMS_WITH_NEW_NODE_IDS_WITH_NEW_NODE_IDS_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_ALGORITHMS_WITH_NEW_NODE_IDS_WITH_NEW_NODE_IDS_H

#include "utils/graph/open_dataflow_graph/open_dataflow_graph_view.h"
#include "utils/graph/open_dataflow_graph/algorithms/with_new_node_ids/with_new_node_ids_result.dtg.h"

namespace FlexFlow {

WithNewNodeIdsResult with_new_node_ids(OpenDataflowGraphView const &);

} // namespace FlexFlow

#endif
