// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/dataflow_graph/dataflow_input.struct.toml
/* proj-data
{
  "generated_from": "d43532deb325bcf8a502efbe90cd287b"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DATAFLOW_GRAPH_DATAFLOW_INPUT_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DATAFLOW_GRAPH_DATAFLOW_INPUT_DTG_H

#include "fmt/format.h"
#include "utils/graph/node/node.dtg.h"
#include <functional>
#include <ostream>
#include <tuple>

namespace FlexFlow {
struct DataflowInput {
  DataflowInput() = delete;
  explicit DataflowInput(::FlexFlow::Node const &node, int const &idx);

  bool operator==(DataflowInput const &) const;
  bool operator!=(DataflowInput const &) const;
  bool operator<(DataflowInput const &) const;
  bool operator>(DataflowInput const &) const;
  bool operator<=(DataflowInput const &) const;
  bool operator>=(DataflowInput const &) const;
  ::FlexFlow::Node node;
  int idx;
};
} // namespace FlexFlow

namespace std {
template <>
struct hash<::FlexFlow::DataflowInput> {
  size_t operator()(::FlexFlow::DataflowInput const &) const;
};
} // namespace std

namespace FlexFlow {
std::string format_as(DataflowInput const &);
std::ostream &operator<<(std::ostream &, DataflowInput const &);
} // namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DATAFLOW_GRAPH_DATAFLOW_INPUT_DTG_H
