// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/dataflow_graph/dataflow_output_query.struct.toml
/* proj-data
{
  "generated_from": "6f662c3c4d285a4fd3c60713e6fc67fa"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DATAFLOW_GRAPH_DATAFLOW_OUTPUT_QUERY_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DATAFLOW_GRAPH_DATAFLOW_OUTPUT_QUERY_DTG_H

#include "fmt/format.h"
#include "utils/graph/node.dtg.h"
#include "utils/graph/query_set.h"
#include <functional>
#include <ostream>
#include <tuple>

namespace FlexFlow {
struct DataflowOutputQuery {
  DataflowOutputQuery() = delete;
  explicit DataflowOutputQuery(
      ::FlexFlow::query_set<::FlexFlow::Node> const &nodes,
      ::FlexFlow::query_set<int> const &output_idxs);

  bool operator==(DataflowOutputQuery const &) const;
  bool operator!=(DataflowOutputQuery const &) const;
  bool operator<(DataflowOutputQuery const &) const;
  bool operator>(DataflowOutputQuery const &) const;
  bool operator<=(DataflowOutputQuery const &) const;
  bool operator>=(DataflowOutputQuery const &) const;
  ::FlexFlow::query_set<::FlexFlow::Node> nodes;
  ::FlexFlow::query_set<int> output_idxs;
};
} // namespace FlexFlow

namespace std {
template <>
struct hash<::FlexFlow::DataflowOutputQuery> {
  size_t operator()(::FlexFlow::DataflowOutputQuery const &) const;
};
} // namespace std

namespace FlexFlow {
std::string format_as(DataflowOutputQuery const &);
std::ostream &operator<<(std::ostream &, DataflowOutputQuery const &);
} // namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DATAFLOW_GRAPH_DATAFLOW_OUTPUT_QUERY_DTG_H
