// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/dataflow_graph/dataflow_edge_query.struct.toml
/* proj-data
{
  "generated_from": "684726a7add4aa912e194335fcfe91ab"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DATAFLOW_GRAPH_DATAFLOW_EDGE_QUERY_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DATAFLOW_GRAPH_DATAFLOW_EDGE_QUERY_DTG_H

#include "fmt/format.h"
#include "utils/graph/node.dtg.h"
#include "utils/graph/query_set.h"
#include <functional>
#include <ostream>
#include <tuple>

namespace FlexFlow {
struct DataflowEdgeQuery {
  DataflowEdgeQuery() = delete;
  explicit DataflowEdgeQuery(
      ::FlexFlow::query_set<::FlexFlow::Node> const &src_nodes,
      ::FlexFlow::query_set<int> const &src_idxs,
      ::FlexFlow::query_set<::FlexFlow::Node> const &dst_nodes,
      ::FlexFlow::query_set<int> const &dst_idxs);

  bool operator==(DataflowEdgeQuery const &) const;
  bool operator!=(DataflowEdgeQuery const &) const;
  bool operator<(DataflowEdgeQuery const &) const;
  bool operator>(DataflowEdgeQuery const &) const;
  bool operator<=(DataflowEdgeQuery const &) const;
  bool operator>=(DataflowEdgeQuery const &) const;
  ::FlexFlow::query_set<::FlexFlow::Node> src_nodes;
  ::FlexFlow::query_set<int> src_idxs;
  ::FlexFlow::query_set<::FlexFlow::Node> dst_nodes;
  ::FlexFlow::query_set<int> dst_idxs;
};
} // namespace FlexFlow

namespace std {
template <>
struct hash<::FlexFlow::DataflowEdgeQuery> {
  size_t operator()(::FlexFlow::DataflowEdgeQuery const &) const;
};
} // namespace std

namespace FlexFlow {
std::string format_as(DataflowEdgeQuery const &);
std::ostream &operator<<(std::ostream &, DataflowEdgeQuery const &);
} // namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DATAFLOW_GRAPH_DATAFLOW_EDGE_QUERY_DTG_H
