// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/open_multidigraph/output_multi_di_edge.struct.toml
/* proj-data
{
  "generated_from": "2ec351b641e8ecfd79fd7df2ec13dbd4"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_MULTIDIGRAPH_OUTPUT_MULTI_DI_EDGE_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_MULTIDIGRAPH_OUTPUT_MULTI_DI_EDGE_DTG_H

#include "fmt/format.h"
#include "utils/graph/node/node.dtg.h"
#include <cstddef>
#include <functional>
#include <ostream>
#include <tuple>

namespace FlexFlow {
struct OutputMultiDiEdge {
  OutputMultiDiEdge() = delete;
  explicit OutputMultiDiEdge(::FlexFlow::Node const &src,
                             size_t const &raw_uid);

  bool operator==(OutputMultiDiEdge const &) const;
  bool operator!=(OutputMultiDiEdge const &) const;
  bool operator<(OutputMultiDiEdge const &) const;
  bool operator>(OutputMultiDiEdge const &) const;
  bool operator<=(OutputMultiDiEdge const &) const;
  bool operator>=(OutputMultiDiEdge const &) const;
  ::FlexFlow::Node src;
  size_t raw_uid;
};
} // namespace FlexFlow

namespace std {
template <>
struct hash<::FlexFlow::OutputMultiDiEdge> {
  size_t operator()(::FlexFlow::OutputMultiDiEdge const &) const;
};
} // namespace std

namespace FlexFlow {
std::string format_as(OutputMultiDiEdge const &);
std::ostream &operator<<(std::ostream &, OutputMultiDiEdge const &);
} // namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_MULTIDIGRAPH_OUTPUT_MULTI_DI_EDGE_DTG_H
