// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/aggregate_op.enum.toml
/* proj-data
{
  "generated_from": "441fe9b0bb8f2dc2b31f74c58320ef30"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_AGGREGATE_OP_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_AGGREGATE_OP_DTG_H

#include "fmt/format.h"
#include "nlohmann/json.hpp"
#include "rapidcheck.h"
#include <functional>
#include <ostream>
#include <string>

namespace FlexFlow {
enum class AggregateOp { SUM };
std::string format_as(AggregateOp);
std::ostream &operator<<(std::ostream &, AggregateOp);
void to_json(::nlohmann::json &, AggregateOp);
void from_json(::nlohmann::json const &, AggregateOp &);
} // namespace FlexFlow
namespace std {
template <>
struct hash<FlexFlow::AggregateOp> {
  size_t operator()(FlexFlow::AggregateOp) const;
};
} // namespace std
namespace rc {
template <>
struct Arbitrary<FlexFlow::AggregateOp> {
  static Gen<FlexFlow::AggregateOp> arbitrary();
};
} // namespace rc

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_AGGREGATE_OP_DTG_H
