// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/pool_op.enum.toml

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_POOL_OP_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_POOL_OP_H

#include "fmt/format.h"
#include "nlohmann/json.hpp"
#include "rapidcheck.h"
#include <functional>
#include <ostream>
#include <string>

namespace FlexFlow {
enum class PoolOp { MAX, AVG };
std::string format_as(PoolOp);
std::ostream &operator<<(std::ostream &, PoolOp);
void to_json(::nlohmann::json &, PoolOp);
void from_json(::nlohmann::json const &, PoolOp &);
} // namespace FlexFlow
namespace std {
template <>
struct hash<FlexFlow::PoolOp> {
  size_t operator()(FlexFlow::PoolOp) const;
};
} // namespace std
namespace rc {
template <>
struct Arbitrary<FlexFlow::PoolOp> {
  static Gen<FlexFlow::PoolOp> arbitrary();
};
} // namespace rc

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_POOL_OP_H
