// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitution-generator/include/substitution-generator/legacy_pm_parameter.enum.toml
/* proj-data
{
  "generated_from": "e8dda0047c91e576878b86df2fec0b6b"
}
*/

#ifndef _FLEXFLOW_LIB_SUBSTITUTION_GENERATOR_INCLUDE_SUBSTITUTION_GENERATOR_LEGACY_PM_PARAMETER_DTG_H
#define _FLEXFLOW_LIB_SUBSTITUTION_GENERATOR_INCLUDE_SUBSTITUTION_GENERATOR_LEGACY_PM_PARAMETER_DTG_H

#include "fmt/format.h"
#include "nlohmann/json.hpp"
#include "rapidcheck.h"
#include <functional>
#include <ostream>
#include <string>

namespace FlexFlow {
enum class LegacyPMParameter {
  OP_TYPE,
  NUM_INPUTS,
  NUM_OUTPUTS,
  GROUP,
  KERNEL_H,
  KERNEL_W,
  STRIDE_H,
  STRIDE_W,
  PADDING_H,
  PADDING_W,
  ACTI,
  NUMDIM,
  AXIS,
  PERM,
  OUTSHUFFLE,
  MERGE_GCONV_COUNT,
  AXES,
  KEEP_DIMS,
  EPSILON,
  REPARTITION_DIM,
  REPARTITION_DEGREE,
  REPLICATE_DIM,
  REPLICATE_DEGREE,
  COMBINE_DIM,
  COMBINE_DEGREE,
  REDUCTION_DIM,
  REDUCTION_DEGREE,
  SOFTMAX_DIM,
  NUM_HEADS,
  PARALLEL_DIM,
  PARALLEL_DEGREE,
  PAD
};
std::string format_as(LegacyPMParameter);
std::ostream &operator<<(std::ostream &, LegacyPMParameter);
void to_json(::nlohmann::json &, LegacyPMParameter);
void from_json(::nlohmann::json const &, LegacyPMParameter &);
} // namespace FlexFlow
namespace std {
template <>
struct hash<FlexFlow::LegacyPMParameter> {
  size_t operator()(FlexFlow::LegacyPMParameter) const;
};
} // namespace std
namespace rc {
template <>
struct Arbitrary<FlexFlow::LegacyPMParameter> {
  static Gen<FlexFlow::LegacyPMParameter> arbitrary();
};
} // namespace rc

#endif // _FLEXFLOW_LIB_SUBSTITUTION_GENERATOR_INCLUDE_SUBSTITUTION_GENERATOR_LEGACY_PM_PARAMETER_DTG_H
