// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/digraph/directed_edge.struct.toml
/* proj-data
{
  "generated_from": "406f818eb74797f6ea07231506a56f81"
}
*/

#include "utils/graph/digraph/directed_edge.dtg.h"

#include <sstream>

namespace FlexFlow {
DirectedEdge::DirectedEdge(::FlexFlow::Node const &src,
                           ::FlexFlow::Node const &dst)
    : src(src), dst(dst) {}
bool DirectedEdge::operator==(DirectedEdge const &other) const {
  return std::tie(this->src, this->dst) == std::tie(other.src, other.dst);
}
bool DirectedEdge::operator!=(DirectedEdge const &other) const {
  return std::tie(this->src, this->dst) != std::tie(other.src, other.dst);
}
bool DirectedEdge::operator<(DirectedEdge const &other) const {
  return std::tie(this->src, this->dst) < std::tie(other.src, other.dst);
}
bool DirectedEdge::operator>(DirectedEdge const &other) const {
  return std::tie(this->src, this->dst) > std::tie(other.src, other.dst);
}
bool DirectedEdge::operator<=(DirectedEdge const &other) const {
  return std::tie(this->src, this->dst) <= std::tie(other.src, other.dst);
}
bool DirectedEdge::operator>=(DirectedEdge const &other) const {
  return std::tie(this->src, this->dst) >= std::tie(other.src, other.dst);
}
} // namespace FlexFlow

namespace std {
size_t hash<FlexFlow::DirectedEdge>::operator()(
    ::FlexFlow::DirectedEdge const &x) const {
  size_t result = 0;
  result ^= std::hash<::FlexFlow::Node>{}(x.src) + 0x9e3779b9 + (result << 6) +
            (result >> 2);
  result ^= std::hash<::FlexFlow::Node>{}(x.dst) + 0x9e3779b9 + (result << 6) +
            (result >> 2);
  return result;
}
} // namespace std

namespace FlexFlow {
std::string format_as(DirectedEdge const &x) {
  std::ostringstream oss;
  oss << "<DirectedEdge";
  oss << " src=" << x.src;
  oss << " dst=" << x.dst;
  oss << ">";
  return oss.str();
}
std::ostream &operator<<(std::ostream &s, DirectedEdge const &x) {
  return s << fmt::to_string(x);
}
} // namespace FlexFlow
