#ifndef _FLEXFLOW_OPATTRS_FFI_INCLUDE_FLEXFLOW_OPATTRS_H
#define _FLEXFLOW_OPATTRS_FFI_INCLUDE_FLEXFLOW_OPATTRS_H

#include "flexflow/utils.h"

FLEXFLOW_FFI_BEGIN()

typedef enum {
  FLEXFLOW_DATATYPE_BOOL,
  FLEXFLOW_DATATYPE_INT32,
  FLEXFLOW_DATATYPE_INT64,
  FLEXFLOW_DATATYPE_HALF,
  FLEXFLOW_DATATYPE_FLOAT,
  FLEXFLOW_DATATYPE_DOUBLE
} flexflow_datatype_t;

FLEXFLOW_FFI_END()

#endif
