// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/views/lr_direction.enum.toml
/* proj-data
{
  "generated_from": "0fef027ec69f92967f3171795ae9ddd2"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_VIEWS_LR_DIRECTION_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_VIEWS_LR_DIRECTION_DTG_H

#include "fmt/format.h"
#include "nlohmann/json.hpp"
#include "rapidcheck.h"
#include <functional>
#include <ostream>
#include <string>

namespace FlexFlow {
enum class LRDirection { LEFT, RIGHT };
std::string format_as(LRDirection);
std::ostream &operator<<(std::ostream &, LRDirection);
void to_json(::nlohmann::json &, LRDirection);
void from_json(::nlohmann::json const &, LRDirection &);
} // namespace FlexFlow
namespace std {
template <>
struct hash<FlexFlow::LRDirection> {
  size_t operator()(FlexFlow::LRDirection) const;
};
} // namespace std
namespace rc {
template <>
struct Arbitrary<FlexFlow::LRDirection> {
  static Gen<FlexFlow::LRDirection> arbitrary();
};
} // namespace rc

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_VIEWS_LR_DIRECTION_DTG_H
