name: flexflow
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6,<3.12
  - cffi>=1.11.0
  - Pillow
  - pybind11
  - rust
  - cmake-build-extension
  - jq
  - pip
  - pip:
    - qualname>=0.1.0
    - keras_preprocessing>=1.1.2
    - numpy>=1.16.0
    - requests
