// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/operator_guid_t.struct.toml
/* proj-data
{
  "generated_from": "348b5a610f4ff6f545884564ee9a1e6a"
}
*/

#ifndef _FLEXFLOW_LIB_PCG_INCLUDE_PCG_OPERATOR_GUID_T_DTG_H
#define _FLEXFLOW_LIB_PCG_INCLUDE_PCG_OPERATOR_GUID_T_DTG_H

#include "fmt/format.h"
#include "utils/graph.h"
#include <functional>
#include <ostream>
#include <tuple>

namespace FlexFlow {
struct operator_guid_t {
  operator_guid_t() = delete;
  operator_guid_t(::FlexFlow::Node const &raw_graph_node);

  bool operator==(operator_guid_t const &) const;
  bool operator!=(operator_guid_t const &) const;
  bool operator<(operator_guid_t const &) const;
  bool operator>(operator_guid_t const &) const;
  bool operator<=(operator_guid_t const &) const;
  bool operator>=(operator_guid_t const &) const;
  ::FlexFlow::Node raw_graph_node;
};
} // namespace FlexFlow

namespace std {
template <>
struct hash<FlexFlow::operator_guid_t> {
  size_t operator()(FlexFlow::operator_guid_t const &) const;
};
} // namespace std

namespace FlexFlow {
std::string format_as(operator_guid_t const &);
std::ostream &operator<<(std::ostream &, operator_guid_t const &);
} // namespace FlexFlow

#endif // _FLEXFLOW_LIB_PCG_INCLUDE_PCG_OPERATOR_GUID_T_DTG_H
