#ifndef _FLEXFLOW_PCG_INCLUDE_PCG_FILE_FORMAT_V1_OP_H
#define _FLEXFLOW_PCG_INCLUDE_PCG_FILE_FORMAT_V1_OP_H

#include "op-attrs/op.h"
#include "utils/json.h"

namespace FlexFlow {

enum class V1Op {
  NOOP,
  INPUT,
  WEIGHT,
  CONV2D,
  DROPOUT,
  LINEAR,
  BATCHMATMUL,
  POOL2D,
  SCALAR_MULTIPLY,
  SCALAR_ADD,
  SCALAR_FLOOR_DIV,
  SCALAR_TRUE_DIV,
  SCALAR_SUB,
  RELU,
  IDENTITY,
  SIGMOID,
  TANH,
  ELU,
  FLAT,
  SOFTMAX,
  BATCHNORM,
  CONCAT,
  SPLIT,
  EMBEDDING,
  GROUP_BY,
  CACHE,
  AGGREGATE,
  AGG_SPEC,
  // OP_ELEMENTWISE,
  RESHAPE,
  REVERSE,
  TRANSPOSE,
  EW_ADD,
  EW_MUL,
  MATMUL,
  MUL,
  ENLARGE,
  SQUEEZE,
  UNSQUEEZE,
  EW_SUB,
  EW_DIV,
  EW_EQUAL,
  EW_GREATER,
  EW_LESS,
  EW_MAX,
  EW_MIN,
  REDUCE_ARGMAX,
  REDUCE_ARGMIN,
  REDUCE_MAX,
  REDUCE_MEAN,
  REDUCE_MIN,
  REDUCE_PROD,
  REDUCE_SUM,
  PAD,
  SHAPE,
  SIZE,
  TOPK,
  WHERE,
  CEIL,
  CAST,
  EXP,
  ROUND,
  LOG,
  LOGICAL_NOT,
  SQRT,
  SIN,
  COS,
  LEAKYRELU,
  SLICE,
  RESIZE,
  PRELU,
  GELU,
  MULTIHEAD_ATTENTION,
  FUSED,
  RSQRT,
  POW,
  MEAN,
  LAYERNORM,
  GATHER,
  BROADCAST,
  REPARTITION,
  COMBINE,
  REPLICATE,
  REDUCTION,
  BATCH,
  PIPELINE,
  FUSED_PARALLEL,
};

NLOHMANN_JSON_SERIALIZE_ENUM(V1Op,
                             {{V1Op::NOOP, "NOOP"},
                              {V1Op::INPUT, "INPUT"},
                              {V1Op::WEIGHT, "WEIGHT"},
                              {V1Op::CONV2D, "CONV2D"},
                              {V1Op::DROPOUT, "DROPOUT"},
                              {V1Op::LINEAR, "LINEAR"},
                              {V1Op::BATCHMATMUL, "BATCHMATMUL"},
                              {V1Op::POOL2D, "POOL2D"},
                              {V1Op::SCALAR_MULTIPLY, "SCALAR_MULTIPLY"},
                              {V1Op::SCALAR_ADD, "SCALAR_ADD"},
                              {V1Op::SCALAR_FLOOR_DIV, "SCALAR_FLOOR_DIV"},
                              {V1Op::SCALAR_TRUE_DIV, "SCALAR_TRUE_DIV"},
                              {V1Op::SCALAR_SUB, "SCALAR_SUB"},
                              {V1Op::RELU, "RELU"},
                              {V1Op::IDENTITY, "IDENTITY"},
                              {V1Op::SIGMOID, "SIGMOID"},
                              {V1Op::TANH, "TANH"},
                              {V1Op::ELU, "ELU"},
                              {V1Op::FLAT, "FLAT"},
                              {V1Op::SOFTMAX, "SOFTMAX"},
                              {V1Op::BATCHNORM, "BATCHNORM"},
                              {V1Op::CONCAT, "CONCAT"},
                              {V1Op::SPLIT, "SPLIT"},
                              {V1Op::EMBEDDING, "EMBEDDING"},
                              {V1Op::GROUP_BY, "GROUP_BY"},
                              {V1Op::CACHE, "CACHE"},
                              {V1Op::AGGREGATE, "AGGREGATE"},
                              {V1Op::AGG_SPEC, "AGG_SPEC"},
                              {V1Op::RESHAPE, "RESHAPE"},
                              {V1Op::REVERSE, "REVERSE"},
                              {V1Op::TRANSPOSE, "TRANSPOSE"},
                              {V1Op::EW_ADD, "EW_ADD"},
                              {V1Op::EW_MUL, "EW_MUL"},
                              {V1Op::MATMUL, "MATMUL"},
                              {V1Op::MUL, "MUL"},
                              {V1Op::ENLARGE, "ENLARGE"},
                              {V1Op::SQUEEZE, "SQUEEZE"},
                              {V1Op::UNSQUEEZE, "UNSQUEEZE"},
                              {V1Op::EW_SUB, "EW_SUB"},
                              {V1Op::EW_DIV, "EW_DIV"},
                              {V1Op::EW_EQUAL, "EW_EQUAL"},
                              {V1Op::EW_GREATER, "EW_GREATER"},
                              {V1Op::EW_LESS, "EW_LESS"},
                              {V1Op::EW_MAX, "EW_MAX"},
                              {V1Op::EW_MIN, "EW_MIN"},
                              {V1Op::REDUCE_ARGMAX, "REDUCE_ARGMAX"},
                              {V1Op::REDUCE_ARGMIN, "REDUCE_ARGMIN"},
                              {V1Op::REDUCE_MAX, "REDUCE_MAX"},
                              {V1Op::REDUCE_MEAN, "REDUCE_MEAN"},
                              {V1Op::REDUCE_MIN, "REDUCE_MIN"},
                              {V1Op::REDUCE_PROD, "REDUCE_PROD"},
                              {V1Op::REDUCE_SUM, "REDUCE_SUM"},
                              {V1Op::PAD, "PAD"},
                              {V1Op::SHAPE, "SHAPE"},
                              {V1Op::SIZE, "SIZE"},
                              {V1Op::TOPK, "TOPK"},
                              {V1Op::WHERE, "WHERE"},
                              {V1Op::CEIL, "CEIL"},
                              {V1Op::CAST, "CAST"},
                              {V1Op::EXP, "EXP"},
                              {V1Op::ROUND, "ROUND"},
                              {V1Op::LOG, "LOG"},
                              {V1Op::LOGICAL_NOT, "LOGICAL_NOT"},
                              {V1Op::SQRT, "SQRT"},
                              {V1Op::SIN, "SIN"},
                              {V1Op::COS, "COS"},
                              {V1Op::LEAKYRELU, "LEAKYRELU"},
                              {V1Op::SLICE, "SLICE"},
                              {V1Op::RESIZE, "RESIZE"},
                              {V1Op::PRELU, "PRELU"},
                              {V1Op::GELU, "GELU"},
                              {V1Op::MULTIHEAD_ATTENTION,
                               "MULTIHEAD_ATTENTION"},
                              {V1Op::FUSED, "FUSED"},
                              {V1Op::RSQRT, "RSQRT"},
                              {V1Op::POW, "POW"},
                              {V1Op::MEAN, "MEAN"},
                              {V1Op::LAYERNORM, "LAYERNORM"},
                              {V1Op::GATHER, "GATHER"},
                              {V1Op::BROADCAST, "BROADCAST"},
                              {V1Op::REPARTITION, "REPARTITION"},
                              {V1Op::COMBINE, "COMBINE"},
                              {V1Op::REPLICATE, "REPLICATE"},
                              {V1Op::REDUCTION, "REDUCTION"},
                              {V1Op::BATCH, "BATCH"},
                              {V1Op::PIPELINE, "PIPELINE"},
                              {V1Op::FUSED_PARALLEL, "FUSED_PARALLEL"}});

V1Op to_v1(Op const &op);

} // namespace FlexFlow

#endif
