#!/bin/bash

. $(dirname $0)/config.linux

SRC_LOCATION=${SRC_LOCATION:=`dirname $0`/../}
CMAKE_COMMAND="${SET_CC_FLAGS} ${SET_NVCC_FLAGS} ${SET_LD_FLAGS} ${SET_CUDA_LIB_PATH} cmake -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF ${SET_CC} ${SET_CXX} ${SET_INSTALL_DIR} ${SET_BUILD} ${SET_CUDA_ARCH} ${SET_CUDA} ${SET_CUDNN} ${SET_PYTHON} ${SET_PIP} ${SET_PYBIND11} ${SET_NCCL} ${SET_GASNET} ${SET_EXAMPLES} ${SET_AVX2} ${SET_MAX_DIM} $* ${SRC_LOCATION}"
echo $CMAKE_COMMAND

eval $CMAKE_COMMAND
