if(EXISTS "/home/ubuntu/repo-refactor/build2/lib/utils/test/utils-test_tests-b858cb2.cmake")
  include("/home/ubuntu/repo-refactor/build2/lib/utils/test/utils-test_tests-b858cb2.cmake")
else()
  add_test(utils-test_NOT_BUILT-b858cb2 utils-test_NOT_BUILT-b858cb2)
endif()
