// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/tensor_pattern/tensor_attribute_list_size.struct.toml
/* proj-data
{
  "generated_from": "ec72cd39de5d1c0f0478696d7b83e4e9"
}
*/

#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_TENSOR_PATTERN_TENSOR_ATTRIBUTE_LIST_SIZE_DTG_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_TENSOR_PATTERN_TENSOR_ATTRIBUTE_LIST_SIZE_DTG_H

#include "fmt/format.h"
#include "nlohmann/json.hpp"
#include "rapidcheck.h"
#include "substitutions/tensor_pattern/tensor_attribute_key.dtg.h"
#include <functional>
#include <ostream>
#include <tuple>

namespace FlexFlow {
struct TensorAttributeListSize {
  TensorAttributeListSize() = delete;
  TensorAttributeListSize(::FlexFlow::TensorAttributeKey const &attribute_key);

  bool operator==(TensorAttributeListSize const &) const;
  bool operator!=(TensorAttributeListSize const &) const;
  bool operator<(TensorAttributeListSize const &) const;
  bool operator>(TensorAttributeListSize const &) const;
  bool operator<=(TensorAttributeListSize const &) const;
  bool operator>=(TensorAttributeListSize const &) const;
  ::FlexFlow::TensorAttributeKey attribute_key;
};
} // namespace FlexFlow

namespace std {
template <>
struct hash<FlexFlow::TensorAttributeListSize> {
  size_t operator()(FlexFlow::TensorAttributeListSize const &) const;
};
} // namespace std

namespace nlohmann {
template <>
struct adl_serializer<FlexFlow::TensorAttributeListSize> {
  static FlexFlow::TensorAttributeListSize from_json(json const &);
  static void to_json(json &, FlexFlow::TensorAttributeListSize const &);
};
} // namespace nlohmann

namespace rc {
template <>
struct Arbitrary<FlexFlow::TensorAttributeListSize> {
  static Gen<FlexFlow::TensorAttributeListSize> arbitrary();
};
} // namespace rc

namespace FlexFlow {
std::string format_as(TensorAttributeListSize const &);
std::ostream &operator<<(std::ostream &, TensorAttributeListSize const &);
} // namespace FlexFlow

#endif // _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_TENSOR_PATTERN_TENSOR_ATTRIBUTE_LIST_SIZE_DTG_H
