// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/unlabelled/unlabelled_graph_pattern.struct.toml
/* proj-data
{
  "generated_from": "7d8730b1ab76f6356bb09084d1c55f06"
}
*/

#include "substitutions/unlabelled/unlabelled_graph_pattern.dtg.h"

namespace FlexFlow {
UnlabelledGraphPattern::UnlabelledGraphPattern(
    ::FlexFlow::OpenDataflowGraphView const &raw_graph)
    : raw_graph(raw_graph) {}
} // namespace FlexFlow
