// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/unlabelled/upward_open_pattern_edge.struct.toml
/* proj-data
{
  "generated_from": "a1d4c9d1dd94eb456c5e29d80ad579da"
}
*/

#include "substitutions/unlabelled/upward_open_pattern_edge.dtg.h"

#include "utils/graph.h"

namespace FlexFlow {
UpwardOpenPatternEdge::UpwardOpenPatternEdge(
    ::FlexFlow::UpwardOpenMultiDiEdge const &raw_edge)
    : raw_edge(raw_edge) {}
bool UpwardOpenPatternEdge::operator==(
    UpwardOpenPatternEdge const &other) const {
  return std::tie(this->raw_edge) == std::tie(other.raw_edge);
}
bool UpwardOpenPatternEdge::operator!=(
    UpwardOpenPatternEdge const &other) const {
  return std::tie(this->raw_edge) != std::tie(other.raw_edge);
}
bool UpwardOpenPatternEdge::operator<(
    UpwardOpenPatternEdge const &other) const {
  return std::tie(this->raw_edge) < std::tie(other.raw_edge);
}
bool UpwardOpenPatternEdge::operator>(
    UpwardOpenPatternEdge const &other) const {
  return std::tie(this->raw_edge) > std::tie(other.raw_edge);
}
bool UpwardOpenPatternEdge::operator<=(
    UpwardOpenPatternEdge const &other) const {
  return std::tie(this->raw_edge) <= std::tie(other.raw_edge);
}
bool UpwardOpenPatternEdge::operator>=(
    UpwardOpenPatternEdge const &other) const {
  return std::tie(this->raw_edge) >= std::tie(other.raw_edge);
}
} // namespace FlexFlow

namespace std {
size_t hash<FlexFlow::UpwardOpenPatternEdge>::operator()(
    FlexFlow::UpwardOpenPatternEdge const &x) const {
  size_t result = 0;
  result ^= std::hash<::FlexFlow::UpwardOpenMultiDiEdge>{}(x.raw_edge) +
            0x9e3779b9 + (result << 6) + (result >> 2);
  return result;
}
} // namespace std
