// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/parallel_tensor_dims_t.struct.toml

#include "op-attrs/parallel_tensor_dims_t.h"

namespace FlexFlow {
ParallelTensorDims::ParallelTensorDims(
    ::FlexFlow::FFOrdered<::FlexFlow::ParallelDim> const &unwrapped)
    : unwrapped(unwrapped) {}
bool ParallelTensorDims::operator==(ParallelTensorDims const &other) const {
  return std::tie(this->unwrapped) == std::tie(other.unwrapped);
}
bool ParallelTensorDims::operator!=(ParallelTensorDims const &other) const {
  return std::tie(this->unwrapped) != std::tie(other.unwrapped);
}
bool ParallelTensorDims::operator<(ParallelTensorDims const &other) const {
  return std::tie(this->unwrapped) < std::tie(other.unwrapped);
}
bool ParallelTensorDims::operator>(ParallelTensorDims const &other) const {
  return std::tie(this->unwrapped) > std::tie(other.unwrapped);
}
bool ParallelTensorDims::operator<=(ParallelTensorDims const &other) const {
  return std::tie(this->unwrapped) <= std::tie(other.unwrapped);
}
bool ParallelTensorDims::operator>=(ParallelTensorDims const &other) const {
  return std::tie(this->unwrapped) >= std::tie(other.unwrapped);
}
} // namespace FlexFlow

namespace std {
size_t hash<FlexFlow::ParallelTensorDims>::operator()(
    FlexFlow::ParallelTensorDims const &x) const {
  size_t result = 0;
  result ^=
      std::hash<::FlexFlow::FFOrdered<::FlexFlow::ParallelDim>>{}(x.unwrapped) +
      0x9e3779b9 + (result << 6) + (result >> 2);
  return result;
}
} // namespace std

namespace nlohmann {
FlexFlow::ParallelTensorDims
    adl_serializer<FlexFlow::ParallelTensorDims>::from_json(json const &j) {
  return {j.at("unwrapped")
              .template get<::FlexFlow::FFOrdered<::FlexFlow::ParallelDim>>()};
}
void adl_serializer<FlexFlow::ParallelTensorDims>::to_json(
    json &j, FlexFlow::ParallelTensorDims const &v) {
  j["__type"] = "ParallelTensorDims";
  j["unwrapped"] = v.unwrapped;
}
} // namespace nlohmann

namespace FlexFlow {
std::string format_as(ParallelTensorDims const &x) {
  std::ostringstream oss;
  oss << "<ParallelTensorDims";
  oss << " unwrapped=" << x.unwrapped;
  oss << ">";
  return oss.str();
}
std::ostream &operator<<(std::ostream &s, ParallelTensorDims const &x) {
  return s << fmt::to_string(x);
}
} // namespace FlexFlow
