// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/open_dataflow_graph/dataflow_graph_input.struct.toml
/* proj-data
{
  "generated_from": "7d6fe1350bb6f70771a7481a8e36aa2e"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_DATAFLOW_GRAPH_INPUT_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_DATAFLOW_GRAPH_INPUT_DTG_H

#include "fmt/format.h"
#include <functional>
#include <ostream>
#include <tuple>

namespace FlexFlow {
struct DataflowGraphInput {
  DataflowGraphInput() = delete;
  explicit DataflowGraphInput(int const &idx);

  bool operator==(DataflowGraphInput const &) const;
  bool operator!=(DataflowGraphInput const &) const;
  bool operator<(DataflowGraphInput const &) const;
  bool operator>(DataflowGraphInput const &) const;
  bool operator<=(DataflowGraphInput const &) const;
  bool operator>=(DataflowGraphInput const &) const;
  int idx;
};
} // namespace FlexFlow

namespace std {
template <>
struct hash<::FlexFlow::DataflowGraphInput> {
  size_t operator()(::FlexFlow::DataflowGraphInput const &) const;
};
} // namespace std

namespace FlexFlow {
std::string format_as(DataflowGraphInput const &);
std::ostream &operator<<(std::ostream &, DataflowGraphInput const &);
} // namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_DATAFLOW_GRAPH_INPUT_DTG_H
