// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/output_graph/output_graph_expr.struct.toml
/* proj-data
{
  "generated_from": "9084c9afb2724504a6f4db4288a83a0d"
}
*/

#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OUTPUT_GRAPH_OUTPUT_GRAPH_EXPR_DTG_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OUTPUT_GRAPH_OUTPUT_GRAPH_EXPR_DTG_H

#include "substitutions/output_graph/output_operator_attrs_assignment.dtg.h"
#include "utils/graph.h"

namespace FlexFlow {
struct OutputGraphExpr {
  OutputGraphExpr() = delete;
  OutputGraphExpr(::FlexFlow::NodeLabelledOpenMultiDiGraph<
                  ::FlexFlow::OutputOperatorAttrsAssignment> const &raw_graph);

  ::FlexFlow::NodeLabelledOpenMultiDiGraph<
      ::FlexFlow::OutputOperatorAttrsAssignment>
      raw_graph;
};
} // namespace FlexFlow

#endif // _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OUTPUT_GRAPH_OUTPUT_GRAPH_EXPR_DTG_H
