// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/pcg_pattern.struct.toml
/* proj-data
{
  "generated_from": "95b0a94000f16024bd541c492bf8a9b1"
}
*/

#include "substitutions/pcg_pattern.dtg.h"

namespace FlexFlow {
PCGPattern::PCGPattern(::FlexFlow::LabelledOpenDataflowGraph<
                       ::FlexFlow::OperatorAttributePattern,
                       ::FlexFlow::TensorAttributePattern> const &raw_graph)
    : raw_graph(raw_graph) {}
} // namespace FlexFlow
