#! /usr/bin/env python3

import sys
from pathlib import Path

DIR = Path(__file__).parent.absolute()

sys.path.append(str(DIR))

from tooling.linting.main import lint_main

lint_main()

# python3 -m tooling.linting -- "$@"
