ff_add_library(
  NAME
    realm-execution
  LANGUAGES
    CXX
    CUDA
  SRC_PATTERNS
    src/*.cc
    src/*.cu
  PUBLIC_INCLUDE
    include/
  PRIVATE_INCLUDE
    src/
  DEPS
    compiler
    kernels
    local-execution
    op-attrs
    pcg
    deps::spdlog
    task-spec
    utils
    deps::realm
)

add_subdirectory(test)
