#ifndef _FLEXFLOW_SUBSTITUTIONS_FFI_INCLUDE_FLEXFLOW_SUBSTITUTIONS_H
#define _FLEXFLOW_SUBSTITUTIONS_FFI_INCLUDE_FLEXFLOW_SUBSTITUTIONS_H

#include "flexflow/utils.h"

FLEXFLOW_FFI_BEGIN()

FLEXFLOW_FFI_END()

#endif
