set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_LIST_DIR}/deps)

include(boost_preprocessor)
include(cuda)
include(cudnn)
include(doctest)
include(fmt)
include(json)
include(legion)
include(nameof)
include(nccl)
include(rapidcheck)
include(spdlog)
include(visit_struct)
