set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_LIST_DIR}/deps)

include(boost_preprocessor)
include(boost_type_index)
include(cuda)
include(cudnn)
include(doctestlib)
include(fmt)
include(json)
include(legion)
include(nameof)
include(nccl)
include(range-v3)
include(rapidcheck)
include(spdlog)
include(visit_struct)
