set(NCCL_NAME nccl)
# set(NCCL_CUDA_ARCH "-gencode=arch=compute_${CUDA_ARCH},code=sm_${CUDA_ARCH}")
# message("NCCL_CUDA_ARCH: ${NCCL_CUDA_ARCH}")

list(TRANSFORM CUDA_GENCODE PREPEND "NVCC_GENCODE=" OUTPUT_VARIABLE NCCL_BUILD_NVCC_GENCODE)

ExternalProject_Add(${NCCL_NAME}
 SOURCE_DIR ${PROJECT_SOURCE_DIR}/deps/${NCCL_NAME}
 PREFIX ${CMAKE_BINARY_DIR}/deps/${NCCL_NAME}
 INSTALL_DIR ${CMAKE_BINARY_DIR}/deps/${NCCL_NAME}
 BUILD_BYPRODUCTS ${CMAKE_BINARY_DIR}/deps/${NCCL_NAME}/lib/libnccl${LIBEXT}
 INSTALL_COMMAND ""
 CONFIGURE_COMMAND ""
 BUILD_COMMAND make src.build "${NCCL_BUILD_NVCC_GENCODE}" "CUDA_HOME=${CUDA_TOOLKIT_ROOT_DIR}" "BUILDDIR=${CMAKE_BINARY_DIR}/deps/${NCCL_NAME}"
 BUILD_IN_SOURCE 1
)

ExternalProject_Get_Property(${NCCL_NAME} INSTALL_DIR)
message(STATUS "NCCL install dir: ${INSTALL_DIR}")
SET(NCCL_INCLUDE_DIR ${INSTALL_DIR}/include)
SET(NCCL_LIB_DIR ${INSTALL_DIR}/lib)
SET(NCCL_SHARE_DIR ${LEGION_BASE_DIR}/share/)

list(APPEND FLEXFLOW_INCLUDE_DIRS ${NCCL_INCLUDE_DIR})
list(APPEND FLEXFLOW_EXT_LIBRARIES ${NCCL_LIB_DIR}/libnccl${LIBEXT})
add_library(${NCCL_NAME} SHARED IMPORTED)
set_target_properties(${NCCL_NAME} PROPERTIES IMPORTED_LOCATION ${NCCL_LIB_DIR}/liblegion${LIBEXT})
set_directory_properties(PROPERTIES ADDITIONAL_CLEAN_FILES "${CMAKE_BINARY_DIR}/deps/${NCCL_NAME}/lib/")

install(DIRECTORY ${NCCL_SHARE_DIR} DESTINATION share)
install(DIRECTORY ${NCCL_LIB_DIR}/ DESTINATION lib)
