name: "gpu-ci-daemon"
on:
  schedule:
    # Run every 5 mins
    - cron: "*/5 * * * *"
  workflow_dispatch:

concurrency:
  group: gpu-ci-daemon-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gpu-ci-daemon:
    name: GPU CI Daemon
    # Prevent Github from running the workflow on forks
    if: github.repository_owner == 'flexflow'
    runs-on: ubuntu-20.04
    env:
      FLEXFLOW_TOKEN: ${{ secrets.FLEXFLOW_TOKEN }}
      FLEXFLOW_RUNNER_INSTANCE_ID: ${{ secrets.FLEXFLOW_RUNNER_INSTANCE_ID }}

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Run daemon
        run: |
          pip3 install pip --upgrade
          pip3 install pyopenssl --upgrade
          pip3 install urllib3 --upgrade
          pip3 install pygithub
          python3 .github/workflows/helpers/gpu_ci_helper.py --daemon
