name: "gpu-ci"
on:
  pull_request:
    paths-ignore:
      - "cmake/**"
      - "config/**"
      - "python/**"
      - "setup.py"
      - "include/**"
      - "src/**"
      - ".github/workflows/gpu-ci.yml"
      - "tests/multi_gpu_tests.sh"
  push:
    branches-ignore:
      - "master"
    paths-ignore:
      - "cmake/**"
      - "config/**"
      - "python/**"
      - "setup.py"
      - "include/**"
      - "src/**"
      - ".github/workflows/gpu-ci.yml"
      - "tests/multi_gpu_tests.sh"
  workflow_dispatch:

concurrency:
  group: gpu-ci-skip-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gpu-ci-flexflow:
    name: Single Machine, Multiple GPUs Tests
    runs-on: ubuntu-20.04
    steps:
      - run: 'echo "No gpu-ci required"'
