name: "gpu-ci"
on:
  pull_request:
    paths-ignore:
      - "cmake/**"
      - "config/**"
      - "deps/**"
      - "python/**"
      - "setup.py"
      - "include/**"
      - "inference/**"
      - "src/**"
      - "tests/inference/**"
      - "conda/flexflow.yml"
      - ".github/workflows/gpu-ci.yml"
      - "tests/cpp_gpu_tests.sh"
      - "tests/inference_tests.sh"
      - "tests/training_tests.sh"
      - "tests/python_interface_test.sh"
  workflow_dispatch:

concurrency:
  group: gpu-ci-skip-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gpu-ci-concierge:
    name: GPU CI Concierge
    runs-on: ubuntu-20.04
    steps:
      - run: 'echo "No gpu-ci required"'

  python-interface-check:
    name: Check Python Interface
    runs-on: ubuntu-20.04
    needs: gpu-ci-concierge
    steps:
      - run: 'echo "No gpu-ci required"'
  
  inference-tests:
    name: Inference Tests
    runs-on: ubuntu-20.04
    needs: gpu-ci-concierge
    steps:
      - run: 'echo "No gpu-ci required"'

  training-tests:
    name: Training Tests
    runs-on: ubuntu-20.04
    # if: ${{ github.event_name != 'pull_request' || github.base_ref != 'inference' }}
    needs: inference-tests
    steps:
      - run: 'echo "No gpu-ci required"'
