name: "oci-control"
on:
  workflow_dispatch:

concurrency:
  group: workflow_test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  my-instances:
    runs-on: ubuntu-latest
    name: Turning on Oracle VM - flexflow-ci
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }} 
      OCI_INSTANCE_ID: ${{ secrets.INSTANCE_ID_FFCI }}
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Install Oci
        run: pip install oci
        
      - name: Running script (START)
        run: python3 docker/oracle_con.py --start --instance_id $OCI_INSTANCE_ID
      