name: "pip-install"
on:
  pull_request:
    paths-ignore:
      - "cmake/**"
      - "config/**"
      - "deps/**"
      - "python/**"
      - "setup.py"
      - "requirements.txt"
      - ".github/workflows/helpers/install_dependencies.sh"
      - ".github/workflows/pip-install.yml"
  workflow_dispatch:
concurrency:
  group: pip-install-skip-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pip-install-flexflow:
    name: Install FlexFlow with pip
    runs-on: ubuntu-20.04
    steps:
      - run: 'echo "No pip-install required"'
