// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/unlabelled/edge_splits.struct.toml
/* proj-data
{
  "generated_from": "f172b041a99f4de1d396e5d451a5e64d"
}
*/

#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_EDGE_SPLITS_DTG_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_EDGE_SPLITS_DTG_H

#include "utils/bidict.h"
#include "utils/graph.h"
#include <tuple>
#include <utility>

namespace FlexFlow {
struct UnlabelledPatternEdgeSplits {
  UnlabelledPatternEdgeSplits() = delete;
  UnlabelledPatternEdgeSplits(
      ::FlexFlow::bidict<::FlexFlow::MultiDiEdge,
                         std::pair<::FlexFlow::OutputMultiDiEdge,
                                   ::FlexFlow::InputMultiDiEdge>> const
          &unwrapped);

  bool operator==(UnlabelledPatternEdgeSplits const &) const;
  bool operator!=(UnlabelledPatternEdgeSplits const &) const;
  ::FlexFlow::bidict<
      ::FlexFlow::MultiDiEdge,
      std::pair<::FlexFlow::OutputMultiDiEdge, ::FlexFlow::InputMultiDiEdge>>
      unwrapped;
};
} // namespace FlexFlow

#endif // _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_EDGE_SPLITS_DTG_H
