// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/unlabelled/match_additional_criterion.struct.toml
/* proj-data
{
  "generated_from": "86e465bc7dbcbece46db9919f4a61a22"
}
*/

#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_MATCH_ADDITIONAL_CRITERION_DTG_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_MATCH_ADDITIONAL_CRITERION_DTG_H

#include "substitutions/unlabelled/pattern_node.dtg.h"
#include "substitutions/unlabelled/pattern_value.dtg.h"
#include "utils/graph/node/node.dtg.h"
#include "utils/graph/open_dataflow_graph/open_dataflow_value.dtg.h"
#include <functional>

namespace FlexFlow {
struct MatchAdditionalCriterion {
  MatchAdditionalCriterion() = delete;
  explicit MatchAdditionalCriterion(
      std::function<bool(::FlexFlow::PatternNode const &,
                         ::FlexFlow::Node const &)> const &node_criterion,
      std::function<bool(::FlexFlow::PatternValue const &,
                         ::FlexFlow::OpenDataflowValue const &)> const
          &value_criterion);

  std::function<bool(::FlexFlow::PatternNode const &, ::FlexFlow::Node const &)>
      node_criterion;
  std::function<bool(::FlexFlow::PatternValue const &,
                     ::FlexFlow::OpenDataflowValue const &)>
      value_criterion;
};
} // namespace FlexFlow

#endif // _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_MATCH_ADDITIONAL_CRITERION_DTG_H
