#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_MATCH_ADDITIONAL_CRITERION_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_MATCH_ADDITIONAL_CRITERION_H

#include "substitutions/unlabelled/match_additional_criterion.dtg.h"

namespace FlexFlow {

MatchAdditionalCriterion match_additional_crition_always_true();

} // namespace FlexFlow

#endif
