// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/unlabelled/output_pattern_edge.struct.toml
/* proj-data
{
  "generated_from": "3222696e351c3e203e008714245c737f"
}
*/

#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_OUTPUT_PATTERN_EDGE_DTG_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_OUTPUT_PATTERN_EDGE_DTG_H

#include "utils/graph.h"
#include <functional>
#include <tuple>

namespace FlexFlow {
struct OutputPatternEdge {
  OutputPatternEdge() = delete;
  OutputPatternEdge(::FlexFlow::OutputMultiDiEdge const &raw_edge);

  bool operator==(OutputPatternEdge const &) const;
  bool operator!=(OutputPatternEdge const &) const;
  bool operator<(OutputPatternEdge const &) const;
  bool operator>(OutputPatternEdge const &) const;
  bool operator<=(OutputPatternEdge const &) const;
  bool operator>=(OutputPatternEdge const &) const;
  ::FlexFlow::OutputMultiDiEdge raw_edge;
};
} // namespace FlexFlow

namespace std {
template <>
struct hash<FlexFlow::OutputPatternEdge> {
  size_t operator()(FlexFlow::OutputPatternEdge const &) const;
};
} // namespace std

#endif // _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_OUTPUT_PATTERN_EDGE_DTG_H
