// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/unlabelled/pattern_edge.struct.toml
/* proj-data
{
  "generated_from": "a3eff166b0c8be2ddf3f7305eec094fd"
}
*/

#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_PATTERN_EDGE_DTG_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_PATTERN_EDGE_DTG_H

#include "utils/graph.h"
#include <functional>
#include <tuple>

namespace FlexFlow {
struct PatternEdge {
  PatternEdge() = delete;
  PatternEdge(::FlexFlow::OpenMultiDiEdge const &raw_edge);

  bool operator==(PatternEdge const &) const;
  bool operator!=(PatternEdge const &) const;
  bool operator<(PatternEdge const &) const;
  bool operator>(PatternEdge const &) const;
  bool operator<=(PatternEdge const &) const;
  bool operator>=(PatternEdge const &) const;
  ::FlexFlow::OpenMultiDiEdge raw_edge;
};
} // namespace FlexFlow

namespace std {
template <>
struct hash<FlexFlow::PatternEdge> {
  size_t operator()(FlexFlow::PatternEdge const &) const;
};
} // namespace std

#endif // _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_PATTERN_EDGE_DTG_H
